spring:
  application:
    name: service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ccut?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
server:
  port: 9999


mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.ccut.mapper: debug