spring:
  application:
    name: service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.96.172.21:3306/ccut?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: ccut
    password: Aa123456
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  ai:
    dashscope:
      api-key: sk-b79bfc6284eb467da714a7957eee7605
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      chat:
        options:
          model: qwen-plus
server:
  port: 9999


mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.ccut.mapper: debug