spring:
  application:
    name: service
  datasource:
    url: jdbc:h2:mem:ccut;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  sql:
    init:
      mode: always
      schema-locations: classpath:SQL.sql
      encoding: UTF-8
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
